#!/usr/bin/env python3
"""
Plant Gene Expression Analysis Pipeline
========================================

A complete bioinformatics pipeline for analyzing plant gene expression data
under abiotic stress conditions.

Usage:
    python run_analysis.py [--data-dir DATA_DIR] [--output-dir OUTPUT_DIR]

This script:
    1. Generates simulated Arabidopsis expression data (or loads existing)
    2. Preprocesses: filters low-expression genes, normalizes, checks for outliers
    3. Analyzes: PCA, differential expression, GO enrichment
    4. Visualizes: PCA plots, volcano plots, heatmaps, marker expression, GO plots
    5. Generates a summary report
"""

import argparse
import sys
import os
from pathlib import Path

# Add project root to Python path
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.data_generation import generate_dataset
from src.preprocessing import run_preprocessing
from src.analysis import run_full_analysis
from src.visualization import generate_all_figures


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plant Gene Expression Analysis Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
    python scripts/run_analysis.py
    python scripts/run_analysis.py --data-dir data --output-dir results
    python scripts/run_analysis.py --no-generate
        """,
    )
    parser.add_argument(
        "--data-dir",
        default=None,
        help="Directory containing expression_data.csv and metadata.csv",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Directory for output files (default: results/)",
    )
    parser.add_argument(
        "--no-generate",
        action="store_true",
        help="Skip data generation if data already exists",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility",
    )
    return parser.parse_args()


def generate_report(
    analysis_results: dict,
    figures: dict,
    output_path: Path,
) -> str:
    """Generate a markdown summary report of the analysis."""
    lines = []
    lines.append("# Plant Gene Expression Analysis Report")
    lines.append("")
    lines.append("*Generated by the automated analysis pipeline*")
    lines.append("")

    # Summary stats
    total_de = 0
    for comp_name, de_df in analysis_results["de_results"].items():
        n_sig = de_df["Significant"].sum()
        n_up = (de_df["Regulation"] == "Up").sum()
        n_down = (de_df["Regulation"] == "Down").sum()
        total_de += n_sig

    lines.append("## Analysis Summary")
    lines.append("")
    lines.append(f"- **Dataset**: Arabidopsis thaliana gene expression (simulated)")
    lines.append(f"- **Conditions**: Control, Drought, Heat, Cold")
    lines.append(f"- **Total DEGs found**: {total_de}")
    lines.append("")

    # PCA results
    var_df = analysis_results["pca"]["variance"]
    lines.append("## PCA Results")
    lines.append("")
    lines.append("| Component | Explained Variance | Cumulative |")
    lines.append("|-----------|-------------------|------------|")
    for _, row in var_df.iterrows():
        lines.append(
            f"| {row['PC']} | {row['Explained_Variance']:.1%} | "
            f"{row['Cumulative_Variance']:.1%} |"
        )
    lines.append("")

    # DE results per comparison
    lines.append("## Differential Expression Results")
    lines.append("")
    for comp_name, de_df in analysis_results["de_results"].items():
        n_up = (de_df["Regulation"] == "Up").sum()
        n_down = (de_df["Regulation"] == "Down").sum()
        display = comp_name.replace("_vs_", " vs ")
        lines.append(f"### {display}")
        lines.append("")
        lines.append(f"- **Upregulated**: {n_up} genes")
        lines.append(f"- **Downregulated**: {n_down} genes")
        lines.append(f"- **Total DEGs**: {n_up + n_down}")
        lines.append("")

        # Top 10 DE genes
        top = de_df[de_df["Significant"]].head(10)
        if not top.empty:
            lines.append("**Top differentially expressed genes:**")
            lines.append("")
            lines.append("| Gene | Log₂FC | Adj. P-value | Regulation |")
            lines.append("|------|--------|-------------|------------|")
            for _, row in top.iterrows():
                lines.append(
                    f"| {row['Gene']} | {row['Log2FC']:.2f} | "
                    f"{row['Adj_P_Value']:.2e} | {row['Regulation']} |"
                )
            lines.append("")

    # GO enrichment
    lines.append("## GO Enrichment Analysis")
    lines.append("")
    for comp_name, go_df in analysis_results["go_results"].items():
        display = comp_name.replace("_vs_", " vs ")
        lines.append(f"### {display}")
        lines.append("")
        if go_df.empty:
            lines.append("No significantly enriched GO terms found.")
        else:
            sig = go_df[go_df["Significant"]]
            if not sig.empty:
                lines.append("**Significantly enriched GO terms:**")
                lines.append("")
                lines.append("| GO Term | Genes | DE Genes | Adj. P-value |")
                lines.append("|---------|-------|----------|-------------|")
                for _, row in sig.head(10).iterrows():
                    lines.append(
                        f"| {row['GO_Term']} | {int(row['Genes_in_Term'])} | "
                        f"{int(row['DE_Genes_in_Term'])} | "
                        f"{row['Adj_P_Value']:.2e} |"
                    )
        lines.append("")

    # Figures
    lines.append("## Generated Figures")
    lines.append("")
    for fig_name, fig_path in figures.items():
        rel_path = os.path.relpath(fig_path, str(output_path.parent))
        lines.append(f"- `{rel_path}`")

    lines.append("")
    lines.append("---")
    lines.append(
        "*This report was automatically generated by the Plant Gene Expression "
        "Analysis Pipeline.*"
    )
    lines.append("")

    report_path = output_path / "analysis_report.md"
    report_path.write_text("\n".join(lines))
    print(f"\n[Report] Analysis report saved to: {report_path}")
    return str(report_path)


def main():
    args = parse_args()

    # Set up directories
    project_root = PROJECT_ROOT
    data_dir = Path(args.data_dir) if args.data_dir else (project_root / "data")
    output_dir = Path(args.output_dir) if args.output_dir else (project_root / "results")

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "figures").mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print(" Plant Gene Expression Analysis Pipeline")
    print("=" * 60)
    print(f" Project root: {project_root}")
    print(f" Data directory: {data_dir}")
    print(f" Output directory: {output_dir}")
    print("=" * 60)

    # Step 1: Data generation/loading
    print("\n>>> STEP 1: DATA GENERATION")
    expr_file = data_dir / "expression_data.csv"
    meta_file = data_dir / "metadata.csv"

    if expr_file.exists() and meta_file.exists() and args.no_generate:
        print("[✓] Loading existing data...")
        import pandas as pd
        expression_df = pd.read_csv(expr_file, index_col=0)
        metadata_df = pd.read_csv(meta_file, index_col=0)
        print(f"    Loaded {expression_df.shape[0]} genes x {expression_df.shape[1]} samples")
    else:
        print("[*] Generating simulated Arabidopsis expression data...")
        expression_df, metadata_df = generate_dataset(
            output_dir=str(data_dir),
            n_genes=5000,
            samples_per_condition=4,
            seed=args.seed,
        )

    print(f"\nExpression matrix: {expression_df.shape[0]} genes, {expression_df.shape[1]} samples")
    print(f"Conditions: {metadata_df['Condition'].unique()}")

    # Step 2: Preprocessing
    print("\n>>> STEP 2: PREPROCESSING")
    preprocessed = run_preprocessing(
        expression_df, metadata_df,
        min_mean=1.0,
        min_samples_pct=0.5,
        normalize=True,
    )

    # Step 3: Analysis
    print("\n>>> STEP 3: ANALYSIS")
    analysis_results = run_full_analysis(
        preprocessed["expression"],
        preprocessed["metadata"],
        control_condition="Control",
        log2fc_threshold=1.0,
        pval_threshold=0.05,
    )

    # Step 4: Visualization
    print("\n>>> STEP 4: VISUALIZATION")
    figures = generate_all_figures(
        preprocessed["expression"],
        preprocessed["metadata"],
        analysis_results,
        str(output_dir / "figures"),
    )

    # Step 5: Report
    print("\n>>> STEP 5: REPORT GENERATION")
    report_path = generate_report(analysis_results, figures, output_dir)

    print("\n" + "=" * 60)
    print(" PIPELINE COMPLETE!")
    print("=" * 60)
    print(f" Results: {output_dir.resolve()}")
    print(f" Report: {report_path}")
    print(f" Figures: {(output_dir / 'figures').resolve()}")
    print("=" * 60)


if __name__ == "__main__":
    main()
